services:
  linkedin_scraper_service:
    build:
      context: ..
      dockerfile: linkedin_scraper_service/Dockerfile
    image: ${MY_IMAGE}
    env_file:
      - .env
    volumes:
      - ./logs:/home/scraper/app/logs
      - ./screenshots:/home/scraper/app/screenshots
      - /var/run/docker.sock:/var/run/docker.sock
      - ../shared:/home/scraper/app/shared:ro
      - ../:/app
    restart: unless-stopped
    ports:
      - "8002:8002"
    platform: linux/amd64
    networks:
      - jobs_alerts_network

networks:
  jobs_alerts_network:
    external: true
