version: '3.8'

services:
  main_project:
    build:
      context: ..
      dockerfile: main_project/Dockerfile
      platforms:
        - linux/amd64
    image: ${MY_IMAGE}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
      - /var/run/docker.sock:/var/run/docker.sock
      - ../shared:/app/shared:ro
    restart: unless-stopped
    ports:
      - "8001:8001" 