version: '3.8'

services:
  main_project:
    build:
      context: ..
      dockerfile: main_project/Dockerfile
    image: ${MY_IMAGE}
    env_file:
      - .env
    volumes:
      - ./logs:/home/scraper/app/logs
      - ./screenshots:/home/scraper/app/screenshots
      - /var/run/docker.sock:/var/run/docker.sock
      - ../shared:/home/scraper/app/shared:ro
      - ./tmp:/tmp
    restart: unless-stopped
    ports:
      - "8001:8001"
    platform: linux/amd64 