services:
  main_project:
    build:
      context: ..
      dockerfile: main_project/Dockerfile
    image: registry.digitalocean.com/mmazurovsky-registry/main_project
    volumes:
      - ./logs:/home/scraper/app/logs
      - ./screenshots:/home/scraper/app/screenshots
      - /var/run/docker.sock:/var/run/docker.sock
      - ../shared:/home/scraper/app/shared:ro
      - ./tmp:/tmp
      - ../:/app
    restart: unless-stopped
    env_file:
      - .env.${ENV}
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LOG_LEVEL=INFO
    ports:
      - "8001:8001"
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8001/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  jobs_alerts_network:
    external: true
