services:
  main_project:
    build:
      context: ..
      dockerfile: main_project/Dockerfile
    image: registry.digitalocean.com/mmazurovsky-registry/main_project
    volumes:
      - ./logs:/home/scraper/app/logs
      - ./screenshots:/home/scraper/app/screenshots
      - /var/run/docker.sock:/var/run/docker.sock
      - ../shared:/home/scraper/app/shared:ro
      - ./tmp:/tmp
      - ../:/app
    restart: unless-stopped
    env_file:
      - .env.${ENVIRONMENT}
    ports:
      - "8001:8001"
    platform: linux/amd64 
    networks:
      - jobs_alerts_network

networks:
  jobs_alerts_network:
    external: true