version: '3.8'

services:
  jobs_alerts:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: ${MY_IMAGE}
    env_file:
      - .env
    volumes:
      - ./logs:/home/scraper/app/logs
      - ./screenshots:/home/scraper/app/screenshots
      - ./state:/home/scraper/app/state
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - "8080:8080" 